[build]
  command = "git clone https://github.com/flutter/flutter.git -b stable --depth 1 $HOME/flutter && export PATH=\"$PATH:$HOME/flutter/bin\" && flutter precache && flutter clean && flutter build web --release --no-tree-shake-icons"
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200